### ISSUE TITLE
api key for the voice support is invalid

### ISSUE THREAD

**Issue by snow-abstraction** [countable/cats-of-jasnah#8]
The api key for the voice support is invalid so the app currently does not talk.

Using Chome dev tools, I see errors such as 

```
responsivevoice.js:126 ResponsiveVoice invalid API key. See https://responsivevoice.org/register?devtools=https%3A%2F%2Fcountable.github.io%2Fcats-of-jasnah%2F
```

(I am filing this issue mainly so other people understand that other have experienced this error. I don't expect people to fix issues on their hobby projects.)

**Comment by countable** [comment]
Thanks for reporting!
