### ISSUE TITLE
Issue with the Union step.

### ISSUE THREAD

**Issue by ronakjain90** [countable/cats-of-jasnah#9]
Hi,

Thanks for this game. My daughter who is 2.10 year old loves it. We play this game weekly once.

I recently saw that you've added more levels to the game, I want to report this issue where there is an error in the Union step.  i.e, level (2-4)

Please see the screenshot attached. The correct answer is 0 but it's wrongly set to 1. Let me know if I can help you with this.

![image](https://user-images.githubusercontent.com/1647009/81817104-d5c79700-9549-11ea-81a7-bc2d7c09060c.png)

**Comment by countable** [comment]
Thanks for the kind words and bug report! My daughter (3 y/o) and I made this game together. We will try to fix the bug.

PS. What do you think of having all these levels with gentler progression? Was it better with just a few levels and steeper progression, before?

**Comment by ronakjain90** [comment]
Well, I'm afraid my answer would be biased since my daughter was at the last level (level 6 I think) before, so I liked the rapid progression. With the newer gentler progression kids would have more time to brush a particular topic thoroughly. 

One fundamental difference between the two versions is that it now auto upgrades the next level when the kids get 5 questions right, but I would have liked it to be a guided progression.
